export const SNACKBAR_SHOW = 'SNACKBAR_SHOW'
export const SNACKBAR_CHANGE_VALUE = 'SNACKBAR_CHANGE_VALUE'

export const APP_CHANGE_VALUE = 'APP_CHANGE_VALUE'

export const FORGOT_PASSWORD_CHANGE_VALUE = 'FORGOT_PASSWORD_CHANGE_VALUE'
export const FORGOT_PASSWORD_CLEAN = 'FORGOT_PASSWORD_CLEAN'

export const SIGN_IN_CHANGE_VALUE = 'SIGN_IN_CHANGE_VALUE'
export const SIGN_IN_CLEAN = 'SIGN_IN_CLEAN'

export const SIGN_UP_CHANGE_VALUE = 'SIGN_UP_CHANGE_VALUE'
export const SIGN_UP_CHANGE_CONFIRM_PASS = 'SIGN_UP_CHANGE_CONFIRM_PASS'
export const SIGN_UP_CLEAN = 'SIGN_UP_CLEAN'

export const CLIENTS_CHANGE_VALUE = 'CLIENTS_CHANGE_VALUE'
export const CLIENTS_CHANGE_LOADING = 'CLIENTS_CHANGE_LOADING'

export const CLIENTS_ADD_EDIT_CHANGE_VALUE = 'CLIENTS_ADD_EDIT_CHANGE_VALUE'
export const CLIENTS_ADD_EDIT_SET = 'CLIENTS_ADD_EDIT_SET'
export const CLIENTS_ADD_EDIT_CHANGE_ERROR = 'CLIENTS_ADD_EDIT_CHANGE_ERROR'
export const CLIENTS_ADD_EDIT_CHANGE_CHILD_VALUE = 'CLIENTS_ADD_EDIT_CHANGE_CHILD_VALUE'
export const CLIENTS_ADD_EDIT_CLEAN = 'CLIENTS_ADD_EDIT_CLEAN'